name: Coding Standards checks
on:
  pull_request:
    branches:
      - '*'

jobs:
  php:
    name: Lint PHP, JavaScript, and CSS files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch.
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org/

      - name: Install NPM root dependencies
        run: npm install

      - name: Install NPM dependencies for the Rareview theme
        run: npm install -w=rareview-theme

      - name: Lint the JS files for the Rareview theme
        run: npm run lint:js -w=rareview-theme

      - name: Lint the JSON files for the Rareview theme
        run: npm run lint:json -w=rareview-theme

      - name: Lint the CSS files for the Rareview theme
        run: npm run lint:style -w=rareview-theme

      - name: Install Composer Dependencies
        run: composer install

      - name: Run Lint
        run: composer lint
